---Silver Table CRM table Creation

IF OBJECT_ID('Silver.CRM_CUST_INFO', 'U') IS NOT NULL
    DROP TABLE Silver.CRM_CUST_INFO;

CREATE TABLE Silver.CRM_CUST_INFO(
CST_ID	INT ,
CST_KEY NVARCHAR(50),
CST_FIRSTNAME NVARCHAR(50),	
CST_LASTNAME NVARCHAR(50),	
CST_MARITAL_STATUS NVARCHAR(50),
CST_GNDR NVARCHAR(50),	
CST_CREATE_DATE DATE,
dwh_create_date DATETIME2 DEFAULT GETDATE()
)


IF OBJECT_ID('SILVER.CRM_PROD_INFO', 'U') IS NOT NULL
    DROP TABLE  SILVER.CRM_PROD_INFO;

CREATE TABLE SILVER.CRM_PROD_INFO(
PRD_ID INT ,
CAT_ID NVARCHAR(50),
PRD_KEY NVARCHAR(50),
PROD_NM NVARCHAR(50),	
PROD_COST INT,
PROD_LINE NVARCHAR(50),
PRD_START_DT DATE,
PRD_END_DT DATE,
DWH_CREATE_DATE DATETIME2 DEFAULT GETDATE()
)

IF OBJECT_ID('Silver.CRM_SALES_DETAILS', 'U') IS NOT NULL
    DROP TABLE  Silver.CRM_SALES_DETAILS;

CREATE TABLE Silver.CRM_SALES_DETAILS(
SLS_ORD_NUM NVARCHAR(50) ,
SLS_PRD_KEY NVARCHAR(50),
SLS_CUST_ID INT,	
SLS_ORDER_DT DATE,
SLS_SHIP_DT DATE,
SLS_DUE_DT DATE,
SLS_SALES INT,	
SLS_QUANTITY INT,	
SLS_PRICE INT,
dwh_create_date DATETIME2 DEFAULT GETDATE()
)

---Silver Table ERP table Creation

IF OBJECT_ID('Silver.ERP_CUST_AZ12', 'U') IS NOT NULL
    DROP TABLE  Silver.ERP_CUST_AZ12;

CREATE TABLE Silver.ERP_CUST_AZ12(
CID VARCHAR(50),
BDATE DATE,
GEN NVARCHAR(50),
dwh_create_date DATETIME2 DEFAULT GETDATE()
)


IF OBJECT_ID('Silver.ERP_LOC_A101', 'U') IS NOT NULL
    DROP TABLE  Silver.ERP_LOC_A101;

CREATE TABLE Silver.ERP_LOC_A101(
CID VARCHAR(20),
CNTRY NVARCHAR(20),
dwh_create_date DATETIME2 DEFAULT GETDATE()
)



IF OBJECT_ID('Silver.ERP_PX_CAT_G1V2', 'U') IS NOT NULL
    DROP TABLE Silver.ERP_PX_CAT_G1V2;

CREATE TABLE Silver.ERP_PX_CAT_G1V2(
ID VARCHAR(50),
CAT NVARCHAR(50),
SUBCAT NVARCHAR(50),
MAINTENANCE NVARCHAR(50),
dwh_create_date DATETIME2 DEFAULT GETDATE()
)
